version: '3'

services:
  ssprocloudserver:
    image: scottyhardy/docker-wine:stable-7.0
    restart: always
    entrypoint: /usr/bin/ssprocloud-entrypoint
    ports:
      - "127.0.0.1:3389:3389/tcp" # RDP (internal, through SSH tunnel only)
      - "1805:1805/tcp" # Pro Cloud Floating License (SSL)
    environment:
      ADMIN: ${ADMIN:-no}  # "yes" or "no"
    volumes:
      - ./winehome:/home/wineuser
      - ./entrypoint.sh:/usr/bin/ssprocloud-entrypoint
      - ./install.sh:/usr/bin/ssprocloud-install
      - ${SSL_CERT}:/home/wineuser/.wine/drive_c/Program Files/Sparx Systems/Pro Cloud Server/Service/server.pem
      - ${SSPROCLOUD_INSTALLER}:/home/wineuser/ssprocloud/ssprocloudserver.msi
